import type { Metadata } from 'next';
import './globals.css';
import { roboto } from '@/config/fonts/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} bg-slate-950`}>{children}</body>
    </html>
  );
}
